name: Test Pull Request

on:
  pull_request:
    branches:
      - master
env:
  GRADLE_USER_HOME: ./.gradle

jobs:
  cancel-previous-pr-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: git fetch --prune --unshallow

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: ${{ env.GRADLE_USER_HOME }}
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Generate local.properties
        run: |
          echo """
          tmdb_api_key=${{ secrets.TMDB_API_KEY }}
          """ > local.properties

      - name: build debug
        run: ./gradlew assembleDebug

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Generate local.properties
        run: |
          echo """
          tmdb_api_key=${{ secrets.TMDB_API_KEY }}
          """ > local.properties

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest --scan

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: unit_test_reports
          path: useCase/build/test-results # path to where the xml test results are stored
